### PR TITLE
Solved UI

### LINKED ISSUE #6: Enhance the Display of AI Section Data with Better Styling
## Description
Currently, the data retrieved from Bard in the **AI Section** is being dumped as plain Markdown. This results in a basic and unappealing display. We need to enhance the presentation of this data to improve readability and user experience.

## Acceptance Criteria
- Data in the **AI Section** is displayed with improved styling and formatting.
- Maintain Markdown support for structured content (e.g., lists, headings, bold text).
- Add visual enhancements like:
  - Consistent fonts and colors.
  - Proper spacing and alignment.
  - Styling for lists, headings, and other Markdown elements.

## Suggested Approach
1. Use a **Markdown renderer** with custom styling to improve the appearance of the content.
2. Leverage Tailwind CSS (or the existing styling framework) to style the rendered Markdown elements.
3. Test the new design with sample Bard data to ensure correctness.

---

### File: `/src/components/AISection.jsx`
- **Update Logic:**
  - Replace the plain Markdown renderer with a styled Markdown renderer (e.g., ReactMarkdown with custom components).
  - Add styles for common Markdown elements (e.g., headings, lists, bold text).

### File: `/src/index.css`
- **Add Styling:**
  - Define CSS classes or Tailwind utilities for:
    - Headings
    - Lists
    - Paragraphs
    - Spacing and alignment

---

### In `AISection.jsx`
Replace the current plain Markdown renderer with enhanced styling:
```javascript
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm"; // Support for tables, task lists, etc.

export default function AiSection({ compoundFormula }) {
  const [res, setResponse] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleGetData = () => {
    setIsLoading(true);
    axios
      .get(`base-url/getinfo/${compoundFormula}`)
      .then((response) => {
        console.log(response.data);
        setResponse(response.data);
        setIsLoading(false);
      })
      .catch((error) => {
        console.error("Error fetching data:", error);
        setIsLoading(false);
      });
  };

  return (
    <div className="overflow-y-scroll p-4 no-scrollbar w-full">
      {isLoading ? (
        <p>Loading...</p>
      ) : (
        <>
          {!res && (
            <button
              onClick={handleGetData}
              className="flex justify-center items-center border-2 border-[#2ABD91] py-2 rounded-full mx-auto cursor-pointer px-6"
            >
              GET DATA
            </button>
          )}
          {res && (
            <ReactMarkdown
              className="prose prose-lg text-white"
              children={res}
              remarkPlugins={[remarkGfm]}
            />
          )}
        </>
      )}
    </div>
  );
}
```
### In `index.css`
Add styles for Markdown elements:
```css
.prose h1 {
  font-size: 1.875rem;
  font-weight: bold;
  color: #2ABD91;
}

.prose h2 {
  font-size: 1.5rem;
  font-weight: semi-bold;
  color: #87CEEB;
}

.prose p {
  font-size: 1rem;
  line-height: 1.5;
  color: #ffffff;
}

.prose ul {
  list-style-type: disc;
  padding-left: 1.5rem;
  color: #ffffff;
}

.prose li {
  margin-bottom: 0.5rem;
}
```

### PR DESCRIPTION
**Pull request by Git-Roshan09**
#### Fixed issues
- Made response look good

#### Changes Made

- In my system the port number is not accessed so i manually gave 5000  (src/components/AISection.jsx)

image

- For my  API gemini 1.0 pro latest is raising some issue so I used 1.5 flash (src/components/AISection.jsx)

- updated Prompt (remove keyword like please and changed alignment and added emojis for good looking) backend/Modules/GPT_Module.js

image

- Made loading button look good  (src/components/AISection.jsx) - used loading button from tailwind website

image

- Created new markdownrender.js file to render markdown response

image

- Addded styling for markdown component (src/app.css)

image

- Markdown function call (src/components/AISection.jsx)

image

#### Demo

image

image

image

### CODE REVIEW

**Comment by TharunKumarrA** [comment]
yo, the new markdown looks really good. Great work man.
but there are some changes I would suggest

**Comment by TharunKumarrA** [comment]
@Twinn-github09 avoid using dangerously set html. Its not a really good practice, since you have separated the markdown rendering part to another component I would suggest you to use react markdown package and customize it for our need

**Comment by TharunKumarrA** [comment]
the system port number and the api endpoint for the ai should be put in an env file, how to do it is given in the readme of the repo. because if the api key is taken from the env file port also shd, just check it once

**Comment by TharunKumarrA** [comment]
can you show me some edge or corner cases for the ai, like for some really unknown molecule or unstable one for example something like C2H or just some ions. Then try for some imaginary compound - how will it handle it?

**Comment by TharunKumarrA** [comment]
also since the whole project is using tailwind, and we dont have like complex css going on can you migrate the markdown css from css file to tailwind

**Comment by TharunKumarrA** [comment]
@Twinn-github09 can you center the get Data button and the processing thing ?
and add some little text below the get data button as of now it is not obvious what data it gets for the user

**Comment by TharunKumarrA** [comment]
Ur missing to show the formula in the prompt we need that too with the name

**Comment by TharunKumarrA** [comment]
#6

**Comment by Git-Roshan09** [comment]
> g part to another component I would suggest you to use react mark

Yea long back I used this for my project, will use react-markdown and i will update here

**Comment by Git-Roshan09** [comment]
> the system port number and the api endpoint for the ai should be put in an env file, how to do it is given in the readme of the repo. because if the api key is taken from the env file port also shd, just check it once

Yess API key is working , i will check that issue for PORT..

**Comment by Git-Roshan09** [comment]
👍 ok i will update react-markdown , with tailwind css, displaying formula of compound and adding info about that get data button

**Comment by TharunKumarrA** [comment]
@Twinn-github09 if you have finished with all the changes that were suggested, Can you share some example pics of the website working?

**Comment by Git-Roshan09** [comment]
### Small Demo

https://github.com/user-attachments/assets/4a2883f6-7b90-4ff8-a05c-09af86998c5b

#### With C6H6

image


#### It is with chemical compund C10H10 it is something new

image


#### With and ion NH4+

image

**Comment by Git-Roshan09** [comment]
### I just updated the prompt and this is output for C10H10

image

### When i enter some imaginary compunds like CO5H

image

**Comment by Git-Roshan09** [comment]
image

**Comment by Git-Roshan09** [comment]
@TharunKumarrA is that ok, if any changes please let me know...

**Comment by TharunKumarrA** [comment]
Great work @Twinn-github09, its has come out really well. Kudos 👏🏽

**Comment by TharunKumarrA** [comment]
@Twinn-github09 i've increased the bounty from 25 to 40 ;)

**Comment by Git-Roshan09** [comment]
Hey @TharunKumarrA  thanks!  It was great working on this project.🫡

**Pull request merged**
